# Generated by Django 5.1.2 on 2024-11-12 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='produtos.categoria'),
        ),
    ]
